spring:
  datasource:
    username: "postgres"
    password: "sebaqx"
    url: "jdbc:postgresql://127.0.0.1:5432/prediction"
    driver-class: "org.postgresql.Driver"


  liquibase:
    change-log: "classpath:liquibase-changeLog.xml"

